/**
 * SYNNR field-ops glossary — programmatic SEO content in our lane. Each term
 * gets its own page (/glossary/[slug]) targeting long-tail searches, with a
 * readiness angle ("why it matters") that generic glossaries don't have.
 */
export type GlossaryTerm = {
  slug: string;
  term: string;
  category: "Field Execution" | "Certs & Compliance" | "Billing & Backup" | "Contracts & Rates";
  def: string;
  why: string;
  related: string[];
};

export const GLOSSARY: GlossaryTerm[] = [
  // ---- Field Execution ----
  { slug: "field-ticket", term: "Field Ticket", category: "Field Execution",
    def: "The document a crew fills out on location recording what was actually done — hours, equipment, consumables, personnel, and customer sign-off. It is the source of truth for what happened on the job and the basis for the invoice.",
    why: "An unsigned or incomplete field ticket is the #1 reason invoices get kicked back. If the ticket doesn't support the charge, the charge doesn't survive review.",
    related: ["job-packet", "ticket-signature", "invoice-backup"] },
  { slug: "job-packet", term: "Job Packet", category: "Field Execution",
    def: "The full bundle of paperwork that proves a job: field tickets, photos, test sheets, permits, JSAs, and sign-offs. Billing builds the invoice from the packet; customers audit against it.",
    why: "A packet missing photos or signatures can hold an entire invoice for weeks. Completeness should be checked before the crew leaves location — not discovered at billing.",
    related: ["field-ticket", "invoice-backup", "pull-test"] },
  { slug: "loadout", term: "Loadout", category: "Field Execution",
    def: "Everything that goes on the truck for a specific job: tools, specialty equipment, consumables, spares, and required paperwork. Loadout lists vary by job type and customer.",
    why: "A missing tool discovered on location means downtime, a hot-shot run, or a failed job. The loadout is the cheapest place to catch a failure — before the truck rolls.",
    related: ["pre-job-checklist", "consumables", "hot-shot"] },
  { slug: "pre-job-checklist", term: "Pre-Job Checklist", category: "Field Execution",
    def: "The verification run before dispatch: right crew, current certs, inspected equipment, correct loadout, customer requirements, and paperwork ready. Often lives in a dispatcher's head or a laminated sheet.",
    why: "Tribal-knowledge checklists fail when the one person who knows is off shift. Written, job-type-specific checks are how readiness survives turnover.",
    related: ["loadout", "competency-matrix", "jsa"] },
  { slug: "standby-time", term: "Standby Time", category: "Field Execution",
    def: "Time a crew or unit spends on location waiting — on the company man, another contractor, weather, or permits — while remaining ready to work. Usually billable at a contracted standby rate.",
    why: "Standby is the most commonly unbilled line in field services. If the ticket logs 6.5 hours waiting and the invoice shows zero, that's real money gone.",
    related: ["missed-billable", "rate-sheet", "field-ticket"] },
  { slug: "mobilization", term: "Mobilization / Demob", category: "Field Execution",
    def: "The cost and effort of getting equipment and crews to and from location. Often a flat contracted fee (mob/demob) or mileage-based charge.",
    why: "Mob fees are routinely forgotten on invoices because they happen before the 'real' work starts. Per-job rules catch them automatically.",
    related: ["rate-sheet", "missed-billable", "call-out"] },
  { slug: "call-out", term: "Call-Out", category: "Field Execution",
    def: "An unscheduled, often after-hours job request. Typically carries premium rates and minimum-hour guarantees under the MSA.",
    why: "Call-out premiums and minimums are easy to miss when the job gets billed like a routine visit. The contract terms only pay if someone applies them.",
    related: ["msa", "rate-sheet", "standby-time"] },
  { slug: "hot-shot", term: "Hot Shot", category: "Field Execution",
    def: "An expedited delivery run — usually a pickup truck or trailer sent urgently with a part, tool, or document that should have been on the original loadout.",
    why: "Every hot shot is a readiness failure with a receipt. Tracking why they happen turns repeat mistakes into loadout rules.",
    related: ["loadout", "pre-job-checklist"] },
  { slug: "company-man", term: "Company Man", category: "Field Execution",
    def: "The operator's on-site representative who supervises the work, signs tickets, and enforces site requirements. Their sign-off is usually required for billing.",
    why: "If the company man leaves before the ticket is signed, the job is done but the invoice is stuck. Sign-off is a before-you-leave check, not a follow-up call.",
    related: ["ticket-signature", "field-ticket"] },
  { slug: "jsa", term: "JSA (Job Safety Analysis)", category: "Field Execution",
    def: "A pre-job safety review that breaks the work into steps, identifies hazards, and assigns controls. Many customers require a completed JSA on file for every job.",
    why: "A missing JSA can invalidate the packet for customers who require it — and it's a compliance exposure if anything goes wrong on location.",
    related: ["job-packet", "tailgate-meeting", "safeland"] },
  { slug: "tailgate-meeting", term: "Tailgate Meeting", category: "Field Execution",
    def: "The short on-site safety briefing before work starts — hazards, roles, escape routes, stop-work authority. Often documented with a sign-in sheet.",
    why: "Customers increasingly audit for documented tailgates. A two-minute signature sheet protects the whole invoice.",
    related: ["jsa", "job-packet"] },

  // ---- Certs & Compliance ----
  { slug: "h2s-certification", term: "H2S Certification", category: "Certs & Compliance",
    def: "Training certification for working in environments where hydrogen sulfide gas may be present. Required on most sour-gas locations; typically expires annually.",
    why: "An expired H2S cert discovered at the gate sends the worker home and can stand the job down. Expirations should be checked against the schedule, not the calendar.",
    related: ["competency-matrix", "safeland", "fit-test"] },
  { slug: "bop-recertification", term: "BOP Recertification", category: "Certs & Compliance",
    def: "Periodic inspection and recertification of blowout preventers and related pressure-control equipment, per regulation and customer policy.",
    why: "Out-of-cert pressure equipment is an automatic stand-down on most locations. The recert date belongs on the dispatch decision, not in a binder.",
    related: ["pull-test", "calibration-certificate"] },
  { slug: "pull-test", term: "Pull Test", category: "Certs & Compliance",
    def: "A documented load test verifying that lifting or pulling equipment (wireline, slickline, crane rigging) holds rated capacity. The pull-test sheet is standard job-packet backup.",
    why: "A missing pull-test sheet is a classic invoice blocker — the work was done, but the proof wasn't captured.",
    related: ["job-packet", "calibration-certificate", "bop-recertification"] },
  { slug: "dot-inspection", term: "DOT Annual Inspection", category: "Certs & Compliance",
    def: "The federally required annual inspection for commercial vehicles. Trucks without a current inspection can't legally run.",
    why: "An out-of-inspection truck assigned to tomorrow's job is a dispatch error waiting to happen. Vehicle status belongs in the same system as the schedule.",
    related: ["calibration-certificate", "pre-job-checklist"] },
  { slug: "calibration-certificate", term: "Calibration Certificate", category: "Certs & Compliance",
    def: "Documentation that a measuring or testing instrument (gauges, torque wrenches, detectors) was calibrated to standard within its required interval.",
    why: "Readings from an out-of-cal tool can be rejected wholesale — taking the job's test results, and the billing they support, down with them.",
    related: ["pull-test", "dot-inspection"] },
  { slug: "safeland", term: "SafeLand / SafeGulf", category: "Certs & Compliance",
    def: "Standardized safety orientation programs widely required for onshore (SafeLand) and offshore (SafeGulf) oil and gas work in the US.",
    why: "Most operators won't let an uncertified hand on location. It's a binary gate on who can be on the crew.",
    related: ["h2s-certification", "competency-matrix"] },
  { slug: "fit-test", term: "Respirator Fit Test", category: "Certs & Compliance",
    def: "An annual test verifying a specific respirator model seals properly on a specific worker's face. Required for jobs where respiratory protection may be needed.",
    why: "Fit tests are personal and expire quietly. They're exactly the kind of requirement that only surfaces when an auditor asks.",
    related: ["h2s-certification", "competency-matrix"] },
  { slug: "competency-matrix", term: "Competency Matrix", category: "Certs & Compliance",
    def: "The grid of who is qualified and current for what: roles, certifications, expiry dates, customer-specific requirements. The answer to 'can this crew legally do this job?'",
    why: "Without a live matrix, crew assignment is memory and hope. With one, an expiring cert pulls a name off the schedule before it becomes a stand-down.",
    related: ["h2s-certification", "safeland", "pre-job-checklist"] },

  // ---- Billing & Backup ----
  { slug: "invoice-backup", term: "Invoice Backup", category: "Billing & Backup",
    def: "The documentation attached to an invoice proving the charges: signed tickets, photos, test sheets, third-party receipts. What the customer's AP team audits before paying.",
    why: "Weak backup is the difference between net-30 and a 90-day dispute. Complete backup at submission is the fastest path to getting paid.",
    related: ["job-packet", "short-pay", "invoice-rejection"] },
  { slug: "ticket-signature", term: "Ticket Signature", category: "Billing & Backup",
    def: "The customer representative's sign-off on the field ticket confirming work performed. On most MSAs, an unsigned ticket is an unbillable ticket.",
    why: "Chasing a signature three weeks later — when the company man has rotated out — is how invoices die. Capture it before leaving location.",
    related: ["company-man", "field-ticket", "invoice-rejection"] },
  { slug: "short-pay", term: "Short Pay", category: "Billing & Backup",
    def: "When a customer pays less than the invoiced amount, disputing or disallowing specific lines — often for missing backup or rate discrepancies.",
    why: "Short pays usually trace to a preventable gap: a rate that didn't match the MSA or a line without proof. Catch those before submission and the short pay never happens.",
    related: ["invoice-rejection", "rate-sheet", "invoice-backup"] },
  { slug: "invoice-rejection", term: "Invoice Rejection", category: "Billing & Backup",
    def: "The customer's AP system kicking an invoice back entirely — wrong PO, missing fields, absent backup, or non-compliant format. The clock on payment restarts from zero.",
    why: "Every rejection adds weeks to DSO. Most rejections are formatting and completeness — fully checkable before you hit send.",
    related: ["short-pay", "purchase-order", "dso"] },
  { slug: "dso", term: "DSO (Days Sales Outstanding)", category: "Billing & Backup",
    def: "The average number of days between doing the work and collecting the cash. The single best measure of how clean your billing pipeline is.",
    why: "Service companies die of cash flow, not losses. Every readiness gap — late tickets, missing backup, disputes — shows up in DSO.",
    related: ["invoice-rejection", "short-pay"] },
  { slug: "missed-billable", term: "Missed Billable", category: "Billing & Backup",
    def: "Work that was performed and documented but never invoiced: standby hours, consumables, mob fees, third-party charges, after-hours premiums.",
    why: "Missed billables are pure margin lost silently. Reconciling tickets against invoices line-by-line is how you find them before the billing window closes.",
    related: ["standby-time", "consumables", "mobilization"] },
  { slug: "consumables", term: "Consumables", category: "Billing & Backup",
    def: "Materials used up on the job — chemicals, straps, blades, gases, fluids. Usually billable at cost-plus or per the price book, if anyone records them.",
    why: "Consumables leak because they're small, numerous, and recorded last. Forty line items at $20 each is $800 per job nobody noticed.",
    related: ["missed-billable", "price-book", "loadout"] },
  { slug: "third-party-charges", term: "Third-Party Charges", category: "Billing & Backup",
    def: "Costs incurred from subcontractors or rentals on a customer's job — cranes, trucking, disposal — typically passed through with markup per the MSA.",
    why: "Third-party invoices arrive after your billing cycle and quietly miss the rebill. A per-job checklist of expected pass-throughs closes the gap.",
    related: ["missed-billable", "msa"] },

  // ---- Contracts & Rates ----
  { slug: "msa", term: "MSA (Master Service Agreement)", category: "Contracts & Rates",
    def: "The umbrella contract between a service company and a customer governing rates, terms, insurance, indemnity, and billing requirements for all work performed.",
    why: "The MSA is where your real rates live. Billing below MSA rates — or violating its backup requirements — costs you on every single job.",
    related: ["rate-sheet", "price-book", "purchase-order"] },
  { slug: "rate-sheet", term: "Rate Sheet", category: "Contracts & Rates",
    def: "The customer-specific schedule of contracted prices: day rates, hourly rates, standby, mileage, equipment charges, and premiums. Usually an exhibit to the MSA.",
    why: "Crews quote from memory and memory is generous to the customer. Every invoice line should be validated against the sheet, not a recollection of it.",
    related: ["msa", "price-book", "short-pay"] },
  { slug: "price-book", term: "Price Book", category: "Contracts & Rates",
    def: "Your internal catalog of everything you charge for, with default rates and units — the master list that customer rate sheets override.",
    why: "If an item isn't in the price book, it doesn't get billed. The book is the difference between charging for what you did and charging for what you remembered.",
    related: ["rate-sheet", "consumables", "missed-billable"] },
  { slug: "purchase-order", term: "PO (Purchase Order)", category: "Contracts & Rates",
    def: "The customer's authorization document for specific work, with a number your invoice must reference. Many AP systems auto-reject invoices without a valid PO.",
    why: "Working without a PO number in hand means billing on hope. Confirm it before dispatch — it's a readiness check like any other.",
    related: ["invoice-rejection", "afe", "msa"] },
  { slug: "afe", term: "AFE (Authorization for Expenditure)", category: "Contracts & Rates",
    def: "The operator's internal budget approval for a project, often referenced on tickets and invoices for cost coding. Customers may require the AFE number on every document.",
    why: "Wrong or missing AFE coding routes your invoice to nobody's budget. It's a five-second check at ticket time and a three-week delay at billing time.",
    related: ["purchase-order", "invoice-rejection"] },
  { slug: "net-terms", term: "Net-30 / Net-60 / Net-90", category: "Contracts & Rates",
    def: "Payment terms defining how long the customer has to pay after receiving a valid invoice. The clock starts only when the invoice is accepted — not when work was done.",
    why: "Net-60 is really net-90 if your invoice bounces once. Clean first-pass submission is the only lever you fully control on payment speed.",
    related: ["dso", "invoice-rejection"] },
];

export const GLOSSARY_CATEGORIES = ["Field Execution", "Certs & Compliance", "Billing & Backup", "Contracts & Rates"] as const;

export function termBySlug(slug: string) {
  return GLOSSARY.find((t) => t.slug === slug);
}
