import { ImageResponse } from "next/og";

// Link-preview image, shown whenever synnr.io is shared in a text, DM, or
// post. Generated by next/og.
export const alt = "SYNNR: every cert in your yard, watched before it lapses";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#131110",
          padding: "72px 80px",
          fontFamily: "sans-serif",
          color: "#ece5d7",
        }}
      >
        <div style={{ display: "flex", fontSize: 40, fontWeight: 700, letterSpacing: -1 }}>SYNNR</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          <div style={{ display: "flex", fontSize: 68, fontWeight: 800, lineHeight: 1.06, letterSpacing: -2, maxWidth: 1000 }}>
            Every cert in your yard, watched before it lapses.
          </div>
          <div style={{ display: "flex", fontSize: 30, color: "#a59d8c", maxWidth: 1000 }}>
            BOP tests, DOT dates, and crew cards on one list. The truck reads NOT READY until the paper is fixed.
          </div>
        </div>
        <div style={{ display: "flex", fontSize: 28, color: "#1d4ed8", fontWeight: 600 }}>synnr.io · $500 per yard, per month</div>
      </div>
    ),
    { ...size },
  );
}
