import { ImageResponse } from "next/og";

// Link-preview image, shown whenever synnr.io is shared in a text, DM, or
// post. Generated by next/og.
export const alt = "SYNNR: every cert in your yard, watched before it lapses";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "linear-gradient(135deg, #0a1633 0%, #0f2a6b 100%)",
          padding: "72px 80px",
          fontFamily: "sans-serif",
          color: "#ffffff",
        }}
      >
        <div style={{ display: "flex", fontSize: 40, fontWeight: 700, letterSpacing: -1 }}>SYNNR</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          <div style={{ display: "flex", fontSize: 68, fontWeight: 800, lineHeight: 1.06, letterSpacing: -2, maxWidth: 1000 }}>
            Every piece of iron. Its serial, where it is, its next test.
          </div>
          <div style={{ display: "flex", fontSize: 30, color: "#c3cde3", maxWidth: 1000 }}>
            BOP stacks, lubricators, valves, and swivels on one list, with QR tags. A warning before anything lapses.
          </div>
        </div>
        <div style={{ display: "flex", fontSize: 28, color: "#9fb7ff", fontWeight: 600 }}>synnr.io · $500 per yard, per month</div>
      </div>
    ),
    { ...size },
  );
}
