import { ImageResponse } from "next/og";

// Branded link-preview image — shown whenever synnr.io is shared in a DM,
// text, Facebook/LinkedIn post, etc. Generated by next/og.
export const alt = "RollReady — catch the miss before the truck leaves the yard";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#0a0a0b",
          padding: "70px 80px",
          fontFamily: "sans-serif",
          color: "#ece5d7",
        }}
      >
        {/* brand */}
        <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
          <div style={{ width: 40, height: 40, background: "#e7ddc7", transform: "rotate(45deg)", borderRadius: 9 }} />
          <div style={{ display: "flex", fontSize: 38, fontWeight: 700, letterSpacing: -1 }}>RollReady</div>
          <div style={{ display: "flex", fontSize: 18, color: "#8a8a82", letterSpacing: 3, textTransform: "uppercase" }}>by SYNNR</div>
        </div>

        {/* headline */}
        <div style={{ display: "flex", flexDirection: "column", gap: 22 }}>
          <div style={{ display: "flex", fontSize: 30, color: "#a59d8c", textTransform: "uppercase", letterSpacing: 5 }}>
            Yard readiness for oilfield service shops
          </div>
          <div style={{ display: "flex", fontSize: 72, fontWeight: 800, lineHeight: 1.04, letterSpacing: -2, maxWidth: 1000 }}>
            Catch the miss before the truck leaves the yard.
          </div>
        </div>

        {/* footer */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              background: "rgba(224,122,63,0.14)",
              border: "1px solid rgba(224,122,63,0.5)",
              borderRadius: 999,
              padding: "10px 22px",
              fontSize: 24,
              fontWeight: 700,
              color: "#e07a3f",
              letterSpacing: 1,
            }}
          >
            NOT READY
          </div>
          <div style={{ display: "flex", fontSize: 27, color: "#e7ddc7", fontWeight: 600 }}>synnr.io · $500 / yard</div>
        </div>
      </div>
    ),
    { ...size },
  );
}
